version: '3.9'
services:
  app:
    build: .
    volumes:
    - .:/app
    ports:
    - 8000:8000
    env_file:
      - ./.env.dev
    image: app:django
    container_name: djnago_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
    - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env.db
    container_name: postgres_db

